name: magic_epaper_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  app_settings: ^6.1.1
  convert: ^3.1.2
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_nfc_kit: ^3.5.2
  flutter_svg_provider: ^1.0.7
  image: ^4.3.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  matrix2d: ^1.0.4
  path_provider: ^2.1.5
  provider: ^6.0.0
  screenshot: ^3.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Roboto Condensed
      fonts:
        - asset: assets/fonts/Roboto_Condensed-Regular.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
